### ISSUE TITLE
关于homework2和上课内容的小建议

### ISSUE THREAD

**Issue by sjtu-liuchao** [shaiic/2019-assignments#40]
建议homework2最后一题提示采用pandas.pivot_table，就像第六题提示采用pandas.crosstab一样；另外建议上课的时候讲解一下pivot_table和crosstab的用法，作业内容最好与上课内容有对应关系。

**Comment by ebluejade** [comment]
顶一下，不过没有关系的好处就是学习范围更大，有关系的好处就是思路是连续的。

**Comment by yangjim** [comment]
感觉一个pivot_table搞定大多数题目了

**Comment by ddebby** [comment]
多谢提意，后续作业的时候尽量考虑完善。库的使用太灵活，很难覆盖全面。
